---
- hosts: vmEjercicios
  vars:
    packages: ["git", "npm"]
  tasks:
   - name: Install packages
     become: true
     become_method: sudo
     apt: 
      name: "{{ packages }}"
      state: present

   - name: clone repository
     become: true
     become_method: sudo
     git: >
      repo=https://github.com/samahetfield/PersonalCC-1819.git
      dest=/home/PersonalCC

   - name: Install dependences
     become: true
     become_method: sudo
     npm:
      path: /home/PersonalCC
